### ISSUE TITLE
Getting error when there is no active subject when using /send command.

### ISSUE THREAD

**Issue by KoStard** [KoStard/TelegramExerciseManager#59]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "runner.py", line 103, in update
    update_bot(bot)
  File "/home/pi/git/TelegramExerciseManager/main/worker.py", line 436, in update_bot
    bot, participant_group, text, message)
  File "/home/pi/git/TelegramExerciseManager/main/worker.py", line 473, in send_problem
    problem: Problem = participant_group.activeSubjectGroupBinding.subject.problem_set.get(
AttributeError: 'NoneType' object has no attribute 'subject'

**Comment by KoStard** [comment]
Fixed.
